### ISSUE TITLE
[BREAKING CHANGE] xcat commands& crontab

### ISSUE THREAD

**Issue by Anankke** [Anankke/SSPanel-Uim#1035]
目前 dev 版本进行了大范围的 command 重构，请升级时注意更新 crontab，详细文档将随后发布。

**Comment by Anankke** [comment]
升级之后请按照以下参考文档重新设定 crontab

```
/**
  * - 可在 Command 文件下添加自定义命令
  * - 类名与文件名一致即可
  * - 如需使用 $argv 请继承 App\Command\Command 类
  * - 无论是否继承都需实现 boot 方法以及 description 属性
  */

当前 php xcat 执行的返回结果，区分大小写，[拥有子项的命令也有单独的提示]：

├─=: php xcat Backup [选项]
│ ├─ full                    - 整体数据备份
│ ├─ simple                  - 只备份核心数据

├─=: php xcat ChenPay [选项]
│ ├─ wxpay                   - Wechat Pay
│ ├─ alipay                  - AliPay

├─=: php xcat DetectBan      - 审计封禁定时任务

├─=: php xcat DetectGFW      - 节点被墙检测定时任务

├─=: php xcat ExtMail [选项]
│ ├─ sendNoMail
│ ├─ sendOldMail

├─=: php xcat FinanceMail [选项]
│ ├─ day                     - 日报
│ ├─ week                    - 周报
│ ├─ month                   - 月报

├─=: php xcat Job [选项]
│ ├─ UserGa                  - 二次验证
│ ├─ DailyJob                - 每日任务
│ ├─ CheckJob                - 检查任务，每分钟
│ ├─ updatedownload          - 检查客户端更新

├─=: php xcat PortAutoChange - 端口被墙则自动更换端口

├─=: php xcat SendDiaryMail  - 每日流量报告

├─=: php xcat SyncRadius [选项]
│ ├─ syncnas
│ ├─ syncvpn
│ ├─ syncusers
│ ├─ synclogin

├─=: php xcat Tool [选项]
│ ├─ initQQWry               - 下载 IP 解析库
│ ├─ setTelegram             - 设置 Telegram 机器人
│ ├─ initdownload            - 下载 SSR 程序至服务器
│ ├─ detectConfigs           - 检查数据库内新增的配置
│ ├─ initdocuments           - 下载用户使用文档至服务器

├─=: php xcat Update         - 更新并迁移配置

├─=: php xcat User [选项]
│ ├─ getCookie               - 获取指定用户的 Cookie
│ ├─ resetPort               - 重置单个用户端口
│ ├─ createAdmin             - 创建管理员帐号
│ ├─ resetAllPort            - 重置所有用户端口
│ ├─ resetTraffic            - 重置所有用户流量
│ ├─ cleanRelayRule          - 清除所有中转规则
```

**Comment by MAOGE2018** [comment]
难怪  php xcat  都失效了！！！
[root@localhost cdn]# php xcat initQQWry
Unable to load class: \App\Command\initQQWry
[root@localhost cdn]# php xcat initdownload
Unable to load class: \App\Command\initdownload

**Comment by MAOGE2018** [comment]
已经使用最新版，发现订阅链接错误了！
Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.

**Comment by Colinwood11** [comment]
> 已经使用最新版，发现订阅链接错误了！
> Slim Application Error
> A website error has occurred. Sorry for the temporary inconvenience.

config里开debug看看输出什么

**Comment by MAOGE2018** [comment]
> > 已经使用最新版，发现订阅链接错误了！
> > Slim Application Error
> > A website error has occurred. Sorry for the temporary inconvenience.
> 
> config里开debug看看输出什么

谢谢提醒：
重启以后还是 订阅链接 Slim Application Error
A website error has occurred. Sorry for the temporary inconvenience.
但是现在好了，问题可能是我节点里面有一个节点被我改成 多用户节点，我改成 ss节点后，订阅链接正常了！
刚刚发现一家好了，

**Comment by MAOGE2018** [comment]
> > 已经使用最新版，发现订阅链接错误了！
> > Slim Application Error
> > A website error has occurred. Sorry for the temporary inconvenience.
> 
> config里开debug看看输出什么

Slim Application Error
The application could not run because of the following error:

Details
Type: ParseError
Message: syntax error, unexpected '}', expecting identifier (T_STRING) or function (T_FUNCTION) or const (T_CONST)
File: /www/wwwroot/cdn/src/Controllers/UserController.php
Line: 12
Trace
#0 /www/wwwroot/cdn/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/www/wwwroot/cd...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Controllers...')
#2 /www/wwwroot/cdn/src/Controllers/AdminController.php(23): spl_autoload_call('App\\Controllers...')
#3 /www/wwwroot/cdn/vendor/composer/ClassLoader.php(444): include('/www/wwwroot/cd...')
#4 /www/wwwroot/cdn/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/www/wwwroot/cd...')
#5 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Controllers...')
#6 [internal function]: spl_autoload_call('App\\Controllers...')
#7 /www/wwwroot/cdn/vendor/slim/slim/Slim/CallableResolver.php(98): class_exists('App\\Controllers...')
#8 /www/wwwroot/cdn/vendor/slim/slim/Slim/CallableResolver.php(58): Slim\CallableResolver->resolveCallable('App\\Controllers...', 'index')
#9 /www/wwwroot/cdn/vendor/slim/slim/Slim/CallableResolverAwareTrait.php(41): Slim\CallableResolver->resolve('App\\Controllers...')
#10 /www/wwwroot/cdn/vendor/slim/slim/Slim/Route.php(276): Slim\Routable->resolveCallable('App\\Controllers...')
#11 /www/wwwroot/cdn/src/Middleware/Admin.php(25): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 [internal function]: App\Middleware\Admin->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#13 /www/wwwroot/cdn/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(App\Middleware\Admin), Array)
#14 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#15 /www/wwwroot/cdn/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#16 /www/wwwroot/cdn/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /www/wwwroot/cdn/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /www/wwwroot/cdn/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 /www/wwwroot/cdn/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php(70): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#20 [internal function]: Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#21 /www/wwwroot/cdn/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware), Array)
#22 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#23 /www/wwwroot/cdn/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#24 /www/wwwroot/cdn/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#25 /www/wwwroot/cdn/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#26 /www/wwwroot/cdn/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#27 /www/wwwroot/cdn/public/index.php(35): Slim\App->run()
#28 {main}

> > 已经使用最新版，发现订阅链接错误了！
> > Slim Application Error
> > A website error has occurred. Sorry for the temporary inconvenience.
> 
> config里开debug看看输出什么

Slim Application Error
The application could not run because of the following error:

Details
Type: ParseError
Message: syntax error, unexpected '}', expecting identifier (T_STRING) or function (T_FUNCTION) or const (T_CONST)
File: /www/wwwroot/cdn/src/Controllers/UserController.php
Line: 12
Trace
#0 /www/wwwroot/cdn/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/www/wwwroot/cd...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Controllers...')
#2 /www/wwwroot/cdn/src/Controllers/AdminController.php(23): spl_autoload_call('App\\Controllers...')
#3 /www/wwwroot/cdn/vendor/composer/ClassLoader.php(444): include('/www/wwwroot/cd...')
#4 /www/wwwroot/cdn/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/www/wwwroot/cd...')
#5 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Controllers...')
#6 [internal function]: spl_autoload_call('App\\Controllers...')
#7 /www/wwwroot/cdn/vendor/slim/slim/Slim/CallableResolver.php(98): class_exists('App\\Controllers...')
#8 /www/wwwroot/cdn/vendor/slim/slim/Slim/CallableResolver.php(58): Slim\CallableResolver->resolveCallable('App\\Controllers...', 'index')
#9 /www/wwwroot/cdn/vendor/slim/slim/Slim/CallableResolverAwareTrait.php(41): Slim\CallableResolver->resolve('App\\Controllers...')
#10 /www/wwwroot/cdn/vendor/slim/slim/Slim/Route.php(276): Slim\Routable->resolveCallable('App\\Controllers...')
#11 /www/wwwroot/cdn/src/Middleware/Admin.php(25): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 [internal function]: App\Middleware\Admin->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#13 /www/wwwroot/cdn/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(App\Middleware\Admin), Array)
#14 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#15 /www/wwwroot/cdn/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#16 /www/wwwroot/cdn/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /www/wwwroot/cdn/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /www/wwwroot/cdn/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 /www/wwwroot/cdn/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php(70): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#20 [internal function]: Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#21 /www/wwwroot/cdn/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware), Array)
#22 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#23 /www/wwwroot/cdn/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#24 /www/wwwroot/cdn/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#25 /www/wwwroot/cdn/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#26 /www/wwwroot/cdn/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#27 /www/wwwroot/cdn/public/index.php(35): Slim\App->run()
#28 {main}

**Comment by Anankke** [comment]
把你爷爷传下来的 PHP 升级了再说

**Comment by Candinya** [comment]
请记得升级 `config/.config.example.php` 第190行的 setTelegram 指令提示 （将`php xcat setTelegram`升级为`php xcat Tool setTelegram`）
我的branch被.htaccess的pull request拒绝毁掉了 ~（我改悔了）~ ，为了防止再造成不必要的审核麻烦，我就不再pull了，麻烦您有空的话帮忙修正一下吧，非常感谢。

**Comment by Anankke** [comment]
> 请记得升级 `config/.config.example.php` 第190行的 setTelegram 指令提示 （将`php xcat setTelegram`升级为`php xcat Tool setTelegram`）
> 我的branch被.htaccess的pull request拒绝毁掉了 ~（我改悔了）~ ，为了防止再造成不必要的审核麻烦，我就不再pull了，麻烦您有空的话帮忙修正一下吧，非常感谢。

你可以直接 `git reset -hard` 然后重新开个分支出来，这没啥麻烦不麻烦的只是我们真的很不想管魔怔阿帕奇（虽然我觉得可能是 plesk 壬所以要搞这个），直接 pr 就是了，可以学习一下 git 这方面的使用方式。

**Comment by waynehung1997** [comment]
> 难怪  php xcat  都失效了！！！
> 
> [root@localhost cdn]# php xcat initQQWry
> 
> Unable to load class: \App\Command\initQQWry
> 
> [root@localhost cdn]# php xcat initdownload
> 
> Unable to load class: \App\Command\initdownload

这个怎么解决呢，现在我卡在php xct creatAdmin这一步下不去了

**Comment by Anankke** [comment]
> > 难怪  php xcat  都失效了！！！
> > [root@localhost cdn]# php xcat initQQWry
> > Unable to load class: \App\Command\initQQWry
> > [root@localhost cdn]# php xcat initdownload
> > Unable to load class: \App\Command\initdownload
> 
> 这个怎么解决呢，现在我卡在php xct creatAdmin这一步下不去了

已ban

**Comment by ningtt** [comment]
Unable to load class: \App\Command\XXX
 这种错误具体怎么解决呢？  自己写文件？ 那方法体里面写什么呢？ 无从下手， 代码全局搜索关键词 都找不到

**Comment by M1Screw** [comment]
@ningtt Upgrade your local panel file.

**Comment by xuelang113** [comment]
教程中的定时任务代码是不是也要修改？我发现现在dev版本的定时任务没有自动更新流量，也没有发送财务报表。
