### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by LexBurner97** [Anankke/SSPanel-Uim#1070]
请将  [ ] 替换为 [x] 。Please relpace [ ] with [x] .

- [ ] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [ ] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [ ] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
CentOS8 Nginx 1.18.0 MySQL 5.6.48 PHP 7.1 phpMyAdmin 4.7

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。
**Bug**
无法进入管理后台和用户中心，可以正常的登陆账号但是无法进行进一步操作

**Reproduce**
通过机场面板进入管理员账号，可以正常登入，点击进入运营后台无法进入显示Slim Application Error

**Logs**
Slim Application Error
The application could not run because of the following error:

Details

Type: ParseError
Message: syntax error, unexpected '}', expecting identifier (T_STRING) or function (T_FUNCTION) or const (T_CONST)
File: /www/wwwroot/pacifique/src/Controllers/UserController.php
Line: 12
Trace

#0 /www/wwwroot/pacifique/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/www/wwwroot/pa...')
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Controllers...')
#2 /www/wwwroot/pacifique/src/Controllers/AdminController.php(23): spl_autoload_call('App\\Controllers...')
#3 /www/wwwroot/pacifique/vendor/composer/ClassLoader.php(444): include('/www/wwwroot/pa...')
#4 /www/wwwroot/pacifique/vendor/composer/ClassLoader.php(322): Composer\Autoload\includeFile('/www/wwwroot/pa...')
#5 [internal function]: Composer\Autoload\ClassLoader->loadClass('App\\Controllers...')
#6 [internal function]: spl_autoload_call('App\\Controllers...')
#7 /www/wwwroot/pacifique/vendor/slim/slim/Slim/CallableResolver.php(98): class_exists('App\\Controllers...')
#8 /www/wwwroot/pacifique/vendor/slim/slim/Slim/CallableResolver.php(58): Slim\CallableResolver->resolveCallable('App\\Controllers...', 'index')
#9 /www/wwwroot/pacifique/vendor/slim/slim/Slim/CallableResolverAwareTrait.php(41): Slim\CallableResolver->resolve('App\\Controllers...')
#10 /www/wwwroot/pacifique/vendor/slim/slim/Slim/Route.php(276): Slim\Routable->resolveCallable('App\\Controllers...')
#11 /www/wwwroot/pacifique/src/Middleware/Admin.php(25): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 [internal function]: App\Middleware\Admin->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#13 /www/wwwroot/pacifique/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(App\Middleware\Admin), Array)
#14 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#15 /www/wwwroot/pacifique/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#16 /www/wwwroot/pacifique/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#17 /www/wwwroot/pacifique/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /www/wwwroot/pacifique/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 /www/wwwroot/pacifique/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php(70): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#20 [internal function]: Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#21 /www/wwwroot/pacifique/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware), Array)
#22 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#23 /www/wwwroot/pacifique/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#24 /www/wwwroot/pacifique/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#25 /www/wwwroot/pacifique/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#26 /www/wwwroot/pacifique/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#27 /www/wwwroot/pacifique/public/index.php(35): Slim\App->run()
#28 {main}

**Comment by Anankke** [comment]
![image](https://user-images.githubusercontent.com/40639066/84223184-5c1ebc80-aaa7-11ea-8d02-849d1e655605.png)
