### ISSUE TITLE
[BUG]手动执行php /www/wwwroot/xcat checkjob报错BUG

### ISSUE THREAD

**Issue by JusufUs** [Anankke/SSPanel-Uim#1112]
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'jsq.telegram_tasks' doesn't exist in /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php:333
Stack trace:
#0 /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php(333): PDO->prepare('select * from `...')
#1 /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select * from `...', Array)
#2 /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#3 /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php(349): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#4 /www/wwwroot/sspanel/vendor/illuminate/database/Query/Builder.php(1610): Illuminate\Database\Connection->select('select * from `...', Array, true)
#5 /www/wwwroot/sspanel/vendor/illuminate/data in /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php on line 729

Fatal error: Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'jsq.telegram_tasks' doesn't exist in /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php:333
Stack trace:
#0 /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php(333): PDO->prepare('select * from `...')
#1 /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'select * from `...', Array)
#2 /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#3 /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php(349): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#4 /www/wwwroot/sspanel/vendor/illuminate/database/Query/Builder.php(1610): Illuminate\Database\Connection->select('select * from `...', Array, true)
#5 /www/wwwroot/sspanel/vendor/illuminate/data in /www/wwwroot/sspanel/vendor/illuminate/database/Connection.php on line 729

**Comment by JusufUs** [comment]
如果是我个人的问题，我出50来个人帮解决下，留TG，谢谢大佬。

**Comment by HynoR** [comment]
50USDT
打到这里，谢谢
0xca3D0BA2225DAb751A9bf322C1Ef7B1a7Ea9aBb5
