### ISSUE TITLE
[BUG] 查看節點訊息時有後端 PHP error

### ISSUE THREAD

**Issue by winwell** [Anankke/SSPanel-Uim#1259]
- [x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
- [x] 我已知晓并同意，我需要把选项前的 [ ] 替换为 [x]。如果我在 x 之前或之后留了空格，则我的 issue 可能会被无条件关闭和锁定。 I acknowledge I have to replace [ ] with [x]. If I leave any space before or after x, my issue could be closed without any notice.
- [x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
- [x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.

**Environment 环境**
Ubuntu 18.04
PHP 7.4

**Commit**
6fefb8060d35640eebcf3cec342ef90fd96c03ac

**Bug**
查看節點訊息時有後端 PHP error

**Reproduce**
新增節點後由用戶中心->節點列表->查看節點

**Logs**
```
Slim Application Error
The application could not run because of the following error:

Details
Type: ParseError
Message: syntax error, unexpected ','
File: /sspanel/src/Utils/AppURI.php
Line: 107
Trace
#0 /sspanel/vendor/composer/ClassLoader.php(346): Composer\Autoload\includeFile()
#1 [internal function]: Composer\Autoload\ClassLoader->loadClass()
#2 /sspanel/src/Utils/URL.php(356): spl_autoload_call()
#3 /sspanel/storage/framework/smarty/compile/2a2c8eb55b9e2131b08b1b87435d05ea7e8dc655_0.file.node_ss_ssr.tpl.php(74): App\Utils\URL::getItemUrl()
#4 /sspanel/vendor/smarty/smarty/libs/sysplugins/smarty_template_resource_base.php(123): content_60a51a3449d880_55248760()
#5 /sspanel/vendor/smarty/smarty/libs/sysplugins/smarty_template_compiled.php(114): Smarty_Template_Resource_Base->getRenderedTemplateCode()
#6 /sspanel/vendor/smarty/smarty/libs/sysplugins/smarty_internal_template.php(216): Smarty_Template_Compiled->render()
#7 /sspanel/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(232): Smarty_Internal_Template->render()
#8 /sspanel/vendor/smarty/smarty/libs/sysplugins/smarty_internal_templatebase.php(134): Smarty_Internal_TemplateBase->_execute()
#9 /sspanel/src/Controllers/User/NodeController.php(138): Smarty_Internal_TemplateBase->display()
#10 [internal function]: App\Controllers\User\NodeController->user_node_info()
#11 /sspanel/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func()
#12 /sspanel/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke()
#13 /sspanel/src/Middleware/Auth.php(26): Slim\Route->__invoke()
#14 [internal function]: App\Middleware\Auth->__invoke()
#15 /sspanel/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#16 [internal function]: Slim\DeferredCallable->__invoke()
#17 /sspanel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#18 /sspanel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}()
#19 /sspanel/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack()
#20 /sspanel/vendor/slim/slim/Slim/App.php(503): Slim\Route->run()
#21 /sspanel/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php(70): Slim\App->__invoke()
#22 [internal function]: Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware->__invoke()
#23 /sspanel/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array()
#24 [internal function]: Slim\DeferredCallable->__invoke()
#25 /sspanel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func()
#26 /sspanel/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}()
#27 /sspanel/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack()
#28 /sspanel/vendor/slim/slim/Slim/App.php(297): Slim\App->process()
#29 /sspanel/public/index.php(37): Slim\App->run()
#30 {main}
```

**Addition**
src/Utils/AppURI.php  Line 107 串接字串多了一個分號
  > ? ', tls=true`'` ,sni=' . $item['host']

應改成
  > ? ', tls=true ,sni=' . $item['host']

**Comment by M1Screw** [comment]
https://github.com/Anankke/SSPanel-Uim/commit/d60ce45c889b1ca1730b587e2ba86d1d55870299 昨天已經修復了。
