### ISSUE TITLE
最新dev后端对接也有BUG

### ISSUE THREAD

**Issue by JusufUs** [Anankke/SSPanel-Uim#1268]
下面是日志，但是我查看了下 'disconnect_ip'这个表是存在的

2021-06-11 16:38:33 ERROR    web_transfer.py:672 Traceback (most recent call last):
  File "/root/shadowsocks/web_transfer.py", line 668, in thread_db
    last_rows, rows)
  File "/root/shadowsocks/web_transfer.py", line 304, in del_server_out_of_bound_safe
    if md5_users[row['id']]['disconnect_ip'] is None:
KeyError: 'disconnect_ip'

**Comment by ding0828** [comment]
同样的问题求解
