### ISSUE TITLE
[BUG] SS订阅异常

### ISSUE THREAD

**Issue by Ruicw** [Anankke/SSPanel-Uim#1575]
**Environment 环境**

OS:    Debian11
PHP version:    8.1
DB version:    mariadb10.7
Commit:    a22a2a6579cb3f31f83a72392fbb47ef7d97b6f2

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。

Slim Application Error
The application could not run because of the following error:

Details
Type: TypeError
Message: App\Models\Node::getItem(): Argument #2 ($mu_port) must be of type int, string given, called in /www/wwwroot/sspanel-uim/src/Utils/URL.php on line 303
File: /www/wwwroot/sspanel-uim/src/Models/Node.php
Line: 329
Trace
#0 /www/wwwroot/sspanel-uim/src/Utils/URL.php(303): App\Models\Node->getItem()
#1 /www/wwwroot/sspanel-uim/src/Utils/URL.php(342): App\Utils\URL::getNewAllItems()
#2 /www/wwwroot/sspanel-uim/src/Controllers/LinkController.php(803): App\Utils\URL::getNewAllUrl()
#3 /www/wwwroot/sspanel-uim/src/Controllers/LinkController.php(163): App\Controllers\LinkController::getSub()
#4 [internal function]: App\Controllers\LinkController::getContent()
#5 /www/wwwroot/sspanel-uim/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func()
#6 /www/wwwroot/sspanel-uim/vendor/slim/slim/Slim/Route.php(344): Slim\Handlers\Strategies\RequestResponse->__invoke()
#7 /www/wwwroot/sspanel-uim/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(116): Slim\Route->__invoke()
#8 /www/wwwroot/sspanel-uim/vendor/slim/slim/Slim/Route.php(316): Slim\Route->callMiddlewareStack()
#9 /www/wwwroot/sspanel-uim/vendor/slim/slim/Slim/App.php(438): Slim\Route->run()
#10 /www/wwwroot/sspanel-uim/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php(70): Slim\App->__invoke()
#11 [internal function]: Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware->__invoke()
#12 /www/wwwroot/sspanel-uim/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array()
#13 [internal function]: Slim\DeferredCallable->__invoke()
#14 /www/wwwroot/sspanel-uim/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(67): call_user_func()
#15 /www/wwwroot/sspanel-uim/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(116): Slim\App->Slim\{closure}()
#16 /www/wwwroot/sspanel-uim/vendor/slim/slim/Slim/App.php(332): Slim\App->callMiddlewareStack()
#17 /www/wwwroot/sspanel-uim/vendor/slim/slim/Slim/App.php(293): Slim\App->process()
#18 /www/wwwroot/sspanel-uim/public/index.php(41): Slim\App->run()
#19 {main}

---------------------------------------------------------------------------------------------------------------------------------------------
new-feat正常使用，因为没有切换到用户功能，重新安装Dev版，导入用户。
承载用户 端口8888  aes-256-gcm origin plain 协议式。。。。
承载节点 地址8888  
奇怪的是直接导入节点链接可以正常使用，订阅下发出错误

**Comment by Ruicw** [comment]
感谢解答，我先用着吧，不行我就换其它的

**Comment by huah6571** [comment]
我也遇到同样问题了2022.11版本，请教一下大佬如何解决的而？
