### ISSUE TITLE
[BUG]Shadowsocks - V2Ray-Plugin  的 ws tls   节点配置无法显示

### ISSUE THREAD

**Issue by XiaoLangCat** [Anankke/SSPanel-Uim#1576]
**Environment 环境**

OS:    Ubuntu 20.04.1 LTS
PHP version:    php 8.0
DB version:    MySQL 10.4.14-MariaDB
Commit:    
a22a2a6579cb3f31f83a72392fbb47ef7d97b6f2

**Bug Info**

用户端该节点配置无法显示。

SHADOWSOCKS
您好，您目前的 加密方式，混淆，或者协议设置在 Shadowsocks 客户端下无法连接。请您选用 ShadowsocksR 客户端来连接，或者到 资料编辑 页面修改后再来查看此处。

 SHADOWSOCKSR
 SHADOWSOCKS
您好，您目前的 加密方式，混淆，或者协议设置在 ShadowsocksR 客户端下无法连接。请您选用 Shadowsocks 客户端来连接，或者到 资料编辑 页面修改后再来查看此处。

同时, ShadowsocksR 单端口多用户的连接不受您设置的影响,您可以在此使用相应的客户端进行连接~

用的XrayR 对接该节点服务器端有一个报错。

: panic: runtime error: index out of range [1] with length 1
9月 08 00:24:47 glowing-tool-1.localdomain XrayR[10247]: goroutine 1 [running]:
9月 08 00:24:47 glowing-tool-1.localdomain XrayR[10247]: github.com/XrayR-project/XrayR/api/sspanel.(*APIClient).ParseSSPluginNodeResponse(0xc000119200, 0xc0000bd800)
9月 08 00:24:47 glowing-tool-1.localdomain XrayR[10247]: github.com/XrayR-project/XrayR/api/sspanel/sspanel.go:529 +0x5b6
9月 08 00:24:47 glowing-tool-1.localdomain XrayR[10247]: github.com/XrayR-project/XrayR/api/sspanel.(*APIClient).GetNodeInfo(0xc000119200)
9月 08 00:24:47 glowing-tool-1.localdomain XrayR[10247]: github.com/XrayR-project/XrayR/api/sspanel/sspanel.go:197 +0x625
9月 08 00:24:47 glowing-tool-1.localdomain XrayR[10247]: github.com/XrayR-project/XrayR/service/controller.(*Controller).Start(0xc0001f4270)
9月 08 00:24:47 glowing-tool-1.localdomain XrayR[10247]: github.com/XrayR-project/XrayR/service/controller/controller.go:58 +0xf5
9月 08 00:24:47 glowing-tool-1.localdomain XrayR[10247]: github.com/XrayR-project/XrayR/panel.(*Panel).Start(0xc000210b80)
9月 08 00:24:47 glowing-tool-1.localdomain XrayR[10247]: github.com/XrayR-project/XrayR/panel/panel.go:196 +0x537
9月 08 00:24:47 glowing-tool-1.localdomain XrayR[10247]: main.main()
9月 08 00:24:47 glowing-tool-1.localdomain XrayR[10247]: github.com/XrayR-project/XrayR/main/main.go:92 +0x1f0
9月 08 00:24:47 glowing-tool-1.localdomain systemd[1]: XrayR.service: main process exited, code=exited, status=2/INVALIDARGUMENT
9月 08 00:24:47 glowing-tool-1.localdomain systemd[1]: Unit XrayR.service entered failed state.
9月 08 00:24:47 glowing-tool-1.localdomain systemd[1]: XrayR.service failed.

Describe the issue you run into. 请描述你遇到的问题。
节点类型：Shadowsocks 
只启用的普通端口

节点地址：
ss006panel.codepay.online;25874;;ws;tls;path=/h48ju7dklf852i|host=ss006panel.codepay.online|server=ss006panel.codepay.online

json编辑器：
{
  "offset_port_user": "25874",
  "offset_port_node": "25874",
  "server_user": "ss006panel.codepay.online",
  "host": "ss006panel.codepay.online",
  "mu_encryption": "chacha20-ietf-poly1305",
  "plugin": "v2ray-plugin",
  "plugin_option": "ws;tls;path=/h48ju7dklf852i"
}

XrayR 配置文件的节点类型是：
NodeType: Shadowsocks-Plugin # Node type: V2ray, Trojan, Shadowsocks, Shadowsocks-Plugin

**Comment by fanqiangvpnnetfree** [comment]
您好，请问这个是怎么回事呀？谢谢您呀
