### ISSUE TITLE
部署 dev 分支 搭建完后创建Trojan节点，在用户的节点列表点开详细显示500错误

### ISSUE THREAD

**Issue by yangliuchang** [Anankke/SSPanel-Uim#1593]
**Environment 环境**

OS:    ubuntu20
PHP version:    8
DB version:    mysql5.7
Commit: c47806a   

**Bug Info**
Slim Application Error
The application could not run because of the following error:

Details
Type: TypeError
Message: App\Models\Node::getArgs(): Return value must be of type array, null returned
File: /www/wwwroot/jc.jsloli.com/src/Models/Node.php
Line: 266
Trace
#0 /www/wwwroot/jc.jsloli.com/src/Models/Node.php(428): App\Models\Node->getArgs()
#1 /www/wwwroot/jc.jsloli.com/src/Controllers/User/NodeController.php(170): App\Models\Node->getTrojanItem()
#2 [internal function]: App\Controllers\User\NodeController->userNodeInfo()
#3 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(41): call_user_func()
#4 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/Route.php(344): Slim\Handlers\Strategies\RequestResponse->__invoke()
#5 /www/wwwroot/jc.jsloli.com/src/Middleware/Auth.php(21): Slim\Route->__invoke()
#6 [internal function]: App\Middleware\Auth->__invoke()
#7 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array()
#8 [internal function]: Slim\DeferredCallable->__invoke()
#9 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(67): call_user_func()
#10 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(116): Slim\Route->Slim\{closure}()
#11 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/Route.php(316): Slim\Route->callMiddlewareStack()
#12 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/App.php(438): Slim\Route->run()
#13 /www/wwwroot/jc.jsloli.com/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php(70): Slim\App->__invoke()
#14 [internal function]: Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware->__invoke()
#15 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/DeferredCallable.php(43): call_user_func_array()
#16 [internal function]: Slim\DeferredCallable->__invoke()
#17 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(67): call_user_func()
#18 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(116): Slim\App->Slim\{closure}()
#19 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/App.php(332): Slim\App->callMiddlewareStack()
#20 /www/wwwroot/jc.jsloli.com/vendor/slim/slim/Slim/App.php(293): Slim\App->process()
#21 /www/wwwroot/jc.jsloli.com/public/index.php(41): Slim\App->run()
#22 {main}

**Comment by yangliuchang** [comment]
添加节点显示200错误，同时会自动清空custom-config；我的custom-config：
{
  "offset_port_user": "8843",
  "offset_port_node": "11361",
  "server_sub": "test.xxx.com",
  "host": "test.xxx.com"
}
