### ISSUE TITLE
[BUG] 初次安装下载客户端报错

### ISSUE THREAD

**Issue by rex5652** [Anankke/SSPanel-Uim#1659]
**Environment 环境**

OS: CentOS 8
PHP version: 8.0
DB version: 10.6
Commit:    68fd9d2

**Bug Info**
初次安装，执行php xcat ClientDownload时出错

本地软体版本库 LocalClientVersion.json 不存在，创建文件中...
====== Clash for Windows 开始 ======
- 本地不存在 Clash for Windows，检测到当前最新版本为 0.20.7
目标文件夹 /data/wwwroot/abc.com/app/../public/clients/ 不存在，创建中...
PHP Fatal error:  Uncaught Error: Call to undefined function App\Command\system() in /data/wwwroot/abc.com/src/Command/ClientDownload.php:53
Stack trace:
#0 /data/wwwroot/abc.com/src/Command/ClientDownload.php(226): App\Command\ClientDownload->getSourceFile()
#1 /data/wwwroot/abc.com/src/Command/ClientDownload.php(41): App\Command\ClientDownload->getSoft()
#2 /data/wwwroot/abc.com/xcat(51): App\Command\ClientDownload->boot()
#3 {main}
  thrown in /data/wwwroot/abc.com/src/Command/ClientDownload.php on line 53

我手动创建了clients文件夹之后再次执行

====== Clash for Windows 开始 ======
- 本地不存在 Clash for Windows，检测到当前最新版本为 0.20.7
- 开始下载 Clash-Windows.exe...
- 下载 Clash-Windows.exe 成功，正在保存...
- 保存 Clash-Windows.exe 至 /data/wwwroot/abc.com/app/../public/clients/ 成功.
PHP Fatal error:  Uncaught Error: Call to undefined function App\Command\system() in /data/wwwroot/abc.com/src/Command/ClientDownload.php:63
Stack trace:
#0 /data/wwwroot/abc.com/src/Command/ClientDownload.php(226): App\Command\ClientDownload->getSourceFile()
#1 /data/wwwroot/abc.com/src/Command/ClientDownload.php(41): App\Command\ClientDownload->getSoft()
#2 /data/wwwroot/abc.com/xcat(51): App\Command\ClientDownload->boot()
#3 {main}
  thrown in /data/wwwroot/abc.com/src/Command/ClientDownload.php on line 63

依然报错，客户端只下载了Clash-Windows.exe

**Comment by chauyuen** [comment]
php里面取消禁用函数system，试试看。

**Comment by rex5652** [comment]
已经是禁用的：
disable_functions = passthru,exec,system,chroot,chgrp,chown,shell_exec,ini_alter,ini_restore,dl,readlink,symlink,popepassthru,stream_socket_server,fsocket,popen

**Comment by rex5652** [comment]
> php里面取消禁用函数system，试试看。

有效，非常感谢
