### ISSUE TITLE
[BUG]11月安装包Dailyjob报错

### ISSUE THREAD

**Issue by lsbjkc** [Anankke/SSPanel-Uim#1661]
用户收到的每日流量使用邮件中的【今日使用流量】总是为0；

每天任务执行完后，用户【登录记录】必报错；

手动执行crontab任务报错如下：
Warning: Attempt to read property "content" on null in /www/wwwroot/example.com/src/Command/Job.php on line 158
Send daily mail to user: 1Send daily mail to user: 3Send daily mail to user: 5Send daily mail to user: 6Send daily mail to user: 7正在下载或更新纯真 IP 数据库...

Warning: file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in /www/wwwroot/example.com/src/Command/Tool.php on line 56

Warning: file_get_contents(): Failed to enable crypto in /www/wwwroot/example.com/src/Command/Tool.php on line 56

Warning: file_get_contents(https://...@latest/qqwry.dat): Failed to open stream: operation failed in /www/wwwroot/example.com/src/Command/Tool.php on line 56

Fatal error: Uncaught TypeError: fwrite(): Argument #2 ($data) must be of type string, bool given in /www/wwwroot/example.com/src/Command/Tool.php:63
Stack trace:
#0 /www/wwwroot/example.com/src/Command/Tool.php(63): fwrite(Resource id #148, false)
#1 /www/wwwroot/example.com/src/Command/Job.php(169): App\Command\Tool->initQQWry()
#2 /www/wwwroot/example.com/src/Command/Job.php(51): App\Command\Job->DailyJob()
#3 /www/wwwroot/example.com/xcat(51): App\Command\Job->boot()
#4 {main}
  thrown in /www/wwwroot/example.com/src/Command/Tool.php on line 63

**Comment by huah6571** [comment]
我用了最新版，TG推送的总流量依然是0

机场小机器人, [2022/11/21 7:24]
今日签到人数：0 
 今日使用总流量：0B

机场小机器人, [2022/11/21 7:24]
成功执行每日任务

机场小机器人, [2022/11/21 7:24]
今日签到人数：0 
 今日使用总流量：0B

机场小机器人, [2022/11/21 7:24]
成功执行每日任务
