### ISSUE TITLE
[BUG] 新用户无法注册

### ISSUE THREAD

**Issue by gbcbooks** [Anankke/SSPanel-Uim#1675]
**Environment 环境**

OS:    ubuntu
PHP version: 8.1.5   
DB version:    maridb
Commit:   用的Release 2022.11

**Bug Info**
新用户注册时，点击TOS同意之后，页面没有反应
Describe the issue you run into. 请描述你遇到的问题。

console 输出为
```
[DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input class=​"form-control maxwidth-auth" id=​"passwd" type=​"password" autocomplete=​"new-password">​
register:1 [DOM] Password field is not contained in a form: (More info: https://goo.gl/9p2vKq) <input class=​"form-control maxwidth-auth" id=​"repasswd" type=​"password" autocomplete=​"new-password">​
project.min.js:1 Uncaught TypeError: Cannot read properties of null (reading 'value')
    at $$getValue (project.min.js:1:51)
    at register (register:203:28)
    at HTMLButtonElement.<anonymous> (register:250:17)
    at HTMLButtonElement.dispatch (jquery.min.js:2:43064)
    at y.handle (jquery.min.js:2:41048)
```

**Comment by gbcbooks** [comment]
问题解决了，如下
修改config.php中，主题改为tabler , 这个release的默认主题是material,  带的project.min.js有问题。
