### ISSUE TITLE
[BUG] 配套的shadowsocks-mod无法正常获取用户

### ISSUE THREAD

**Issue by gbcbooks** [Anankke/SSPanel-Uim#1677]
**Environment 环境**

OS:    ubuntu 20.04
PHP version:    8.1.5
DB version:    MariaDB
Commit:    SSPANEL 2022.11

**Bug Info**

Describe the issue you run into. 请描述你遇到的问题。

用webapi可正常连上，PANEL可以看到节点上来，但是节点无法获取用户

```
ssmod  | 2022-11-25 01:14:03 ERROR    webapi_utils.py:27 Server error with status code: 404
ssmod  | 2022-11-25 01:14:03 ERROR    web_transfer.py:543 Traceback (most recent call last):
ssmod  |   File "/app/web_transfer.py", line 536, in thread_db
ssmod  |     rows = db_instance.pull_db_all_user()
ssmod  |   File "/app/web_transfer.py", line 185, in pull_db_all_user
ssmod  |     data = webapi.getApi("nodes")
ssmod  |   File "/app/webapi_utils.py", line 29, in getApi
ssmod  |     raise Exception('Server Error!')
ssmod  | Exception: Server Error!
ssmod  | 
```
用curl，得404
```
curl -v "http://10.100.1.10/mod_mu/nodes?key=mukeyoverapi"                                                                                                  ✔ 
*   Trying 10.100.1.10:80...
* Connected to 10.100.1.10 (10.100.1.10) port 80 (#0)
> GET /mod_mu/nodes?key=mukeyoverapi HTTP/1.1
> Host: 10.100.1.10
> User-Agent: curl/7.86.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Server: nginx/1.21.4
< Date: Fri, 25 Nov 2022 01:07:02 GMT
< Content-Type: text/html; charset=UTF-8
< Content-Length: 466
< Connection: keep-alive
< Vary: Accept-Encoding
< X-Powered-By: PHP/8.1.5
< 
<!DOCTYPE HTML>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Not Found - SSPanel-UIM</title>
    <link rel="shortcut icon" href="/favicon.ico"/>
    <link rel="bookmark" href="/favicon.ico" type="image/x-icon"/>
    <link rel="stylesheet" href="/assets/css/error-pages.min.css"/>
</head>
<body>
<div class="container">
    <div class="copy-container center-xy">
        <p>
            404, Not Found.
        </p>
    </div>
</div>
</body>
</html>
* Connection #0 to host 10.100.1.10 left intact
```

**Comment by gbcbooks** [comment]
反馈一下，用Release 2022-10的版 本， 可以正常获取nodes 
```
# curl -v -X GET "http://10.100.1.10/mod_mu/nodes?key=mukeyoverapi"                                            ✔ 
Note: Unnecessary use of -X or --request, GET is already inferred.
*   Trying 10.100.1.10:80...
* Connected to 10.100.1.10 (10.100.1.10) port 80 (#0)
> GET /mod_mu/nodes?key=mukeyoverapi HTTP/1.1
> Host: 10.100.1.10
> User-Agent: curl/7.86.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 200 OK
< Server: nginx/1.21.4
< Date: Fri, 25 Nov 2022 17:34:25 GMT
< Content-Type: application/json;charset=utf-8
< Content-Length: 483
< Connection: keep-alive
< Vary: Accept-Encoding
< X-Powered-By: PHP/8.1.5
< ETAG: 0d40db74
< WebAPI-ETAG: 0d40db74
< 
* Connection #0 to host 10.100.1.10 left intact
{"ret":1,"data":[{"id":1,"name":"CN \u56fd\u5185\u6d4b\u8bd5 manjaro","type":true,"server":"","custom_config":"{}","info":"\u65e0\u63cf\u8ff0","status":"\u53ef\u7528","sort":0,"traffic_rate":1,"node_class":0,"node_speedlimit":0,"node_connector":0,"node_bandwidth":0,"node_bandwidth_limit":0,"bandwidthlimit_resetday":1,"node_heartbeat":0,"node_ip":"10.8.15.15","node_group":0,"mu_only":-1,"online":1,"gfw_block":0,"password":"121a79d625da6443676bf63910b06e81","load":"","uptime":0}]}%        
```

**Comment by gbcbooks** [comment]
用户无法注册和这个无法获取nodes信息的这两个问题，把我整死了哈，爆肝了三个通宵。
