### ISSUE TITLE
[BUG] 2022.12 全新安裝生成數據庫結構時報錯

### ISSUE THREAD

**Issue by NekoCloudServices** [Anankke/SSPanel-Uim#1695]
Environment 環境

OS: Debian 11 Bullseye stable
PHP version: PHP 8.0 with OPcache
DB version: MariaDB 10.6
Commit: 2022.12 (49a29d28b766952f2858159b6145c40cbaf37e83)

Bug Info

Describe the issue you run into. 請描述你遇到的問題。

復現步驟：按照官方教程 https://wiki.sspanel.org/#/install-using-oneinstack 全新安裝 2022.12 版本，進行至 php vendor/bin/phinx migrate 步骤，即會報錯.....（已確認配置文件數據庫賬號密碼填寫正確，能夠通過PHPMyAdmin正常登錄）

錯誤日誌：
```
root@debian:/data/wwwroot/test.com# php vendor/bin/phinx migrate
Phinx by CakePHP - https://phinx.org.

using config file phinx.php
using config parser php
using migration paths 
 - /data/wwwroot/test.com/db/migrations
using seed paths 
 - /data/wwwroot/test.com/db/seeds
warning no environment specified, defaulting to: production
using adapter mysql
using database sspanel
ordering by creation time

 == 20220505044345 StringToText: migrating 
PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'markdown' in 'announcement' in /data/wwwroot/test.com/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php:192
Stack trace:
#0 /data/wwwroot/test.com/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(192): PDO->exec()
#1 /data/wwwroot/test.com/vendor/robmorgan/phinx/src/Phinx/Db/Util/AlterInstructions.php(108): Phinx\Db\Adapter\PdoAdapter->execute()
#2 /data/wwwroot/test.com/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(626): Phinx\Db\Util\AlterInstructions->execute()
#3 /data/wwwroot/test.com/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/PdoAdapter.php(1001): Phinx\Db\Adapter\PdoAdapter->executeAlterSteps()
#4 /data/wwwroot/test.com/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/AdapterWrapper.php(477): Phinx\Db\Adapter\PdoAdapter->executeActions()
#5 /data/wwwroot/test.com/vendor/robmorgan/phinx/src/Phinx/Db/Adapter/TimedOutputAdapter.php(420): Phinx\Db\Adapter\AdapterWrapper->executeActions()
#6 /data/wwwroot/test.com/vendor/robmorgan/phinx/src/Phinx/Db/Plan/Plan.php(151): Phinx\Db\Adapter\TimedOutputAdapter->executeActions()
#7 /data/wwwroot/test.com/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(716): Phinx\Db\Plan\Plan->execute()
#8 /data/wwwroot/test.com/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(624): Phinx\Db\Table->executeActions()
#9 /data/wwwroot/test.com/vendor/robmorgan/phinx/src/Phinx/Db/Table.php(683): Phinx\Db\Table->update()
#10 /data/wwwroot/test.com/db/migrations/20220505044345_string_to_text.php(30): Phinx\Db\Table->save()
#11 /data/wwwroot/test.com/vendor/robmorgan/phinx/src/Phinx/Migration/Manager/Environment.php(111): StringToText->up()
#12 /data/wwwroot/test.com/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(388): Phinx\Migration\Manager\Environment->executeMigration()
#13 /data/wwwroot/test.com/vendor/robmorgan/phinx/src/Phinx/Migration/Manager.php(359): Phinx\Migration\Manager->executeMigration()
#14 /data/wwwroot/test.com/vendor/robmorgan/phinx/src/Phinx/Console/Command/Migrate.php(122): Phinx\Migration\Manager->migrate()
#15 /data/wwwroot/test.com/vendor/symfony/console/Command/Command.php(291): Phinx\Console\Command\Migrate->execute()
#16 /data/wwwroot/test.com/vendor/symfony/console/Application.php(1014): Symfony\Component\Console\Command\Command->run()
#17 /data/wwwroot/test.com/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand()
#18 /data/wwwroot/test.com/vendor/robmorgan/phinx/src/Phinx/Console/PhinxApplication.php(70): Symfony\Component\Console\Application->doRun()
#19 /data/wwwroot/test.com/vendor/symfony/console/Application.php(171): Phinx\Console\PhinxApplication->doRun()
#20 /data/wwwroot/test.com/vendor/robmorgan/phinx/bin/phinx(28): Symfony\Component\Console\Application->run()
#21 /data/wwwroot/test.com/vendor/bin/phinx(120): include('...')
#22 {main}
```

**Comment by syouko** [comment]
完全一样的错误，尝试过不同MariaDB[10.6 10.10]和PHP[8.0 8.1]版本均不可。
