### ISSUE TITLE
[BUG] 数据库升级报错IF NOT EXISTS `gateway` varchar(255) NOT NULL DEFAULT ''' 

### ISSUE THREAD

**Issue by 34556676** [Anankke/SSPanel-Uim#1834]
**Environment 环境**

OS:    centos7.9
PHP version:    8.2
DB version:    8.0
Commit:    

**Bug Info**

Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `gateway` varchar(255) NOT NULL DEFAULT ''' at line 1 in /www/wwwroot/sspanel/db/migrations/2023031701-add_paylist_gateway.php:11

**Comment by 34556676** [comment]
BLOB, TEXT, GEOMETRY or JSON column 'remark' can't have a default value

**Comment by 34556676** [comment]
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `gateway` varchar(255) NOT NULL DEFAULT ''' at line 1 in /www/wwwroot/sspanel/db/migrations/2023031701-add_paylist_gateway.php:11
Stack trace:
#0 /www/wwwroot/sspanel/db/migrations/2023031701-add_paylist_gateway.php(11): PDO->exec()
#1 /www/wwwroot/sspanel/src/Command/Migration.php(103): App\Interfaces\MigrationInterface@anonymous->up()
#2 /www/wwwroot/sspanel/xcat(51): App\Command\Migration->boot()
#3 {main}
  thrown in /www/wwwroot/sspanel/db/migrations/2023031701-add_paylist_gateway.php on line 11

Fatal error: Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF NOT EXISTS `gateway` varchar(255) NOT NULL DEFAULT ''' at line 1 in /www/wwwroot/sspanel/db/migrations/2023031701-add_paylist_gateway.php:11
Stack trace:
#0 /www/wwwroot/sspanel/db/migrations/2023031701-add_paylist_gateway.php(11): PDO->exec()
#1 /www/wwwroot/sspanel/src/Command/Migration.php(103): App\Interfaces\MigrationInterface@anonymous->up()
#2 /www/wwwroot/sspanel/xcat(51): App\Command\Migration->boot()
#3 {main}
  thrown in /www/wwwroot/sspanel/db/migrations/2023031701-add_paylist_gateway.php on line 11
@M1Screw

**Comment by 34556676** [comment]
这个不修修吗

**Comment by M1Screw** [comment]
關閉嚴格模式。

**Comment by 34556676** [comment]
试过了，sql_mode都清空了

**Comment by 34556676** [comment]
已解决。宝塔用户修改mysql配置文件参数：sql_mode=NO_ENGINE_SUBSTITUTION
