### ISSUE TITLE
升级到最新DEV分支后获取CLASH订阅出错

### ISSUE THREAD

**Issue by lowprofileusername** [Anankke/SSPanel-Uim#1858]
Slim Application Error

The application could not run because of the following error:
Details
Type: TypeError
Code: 0
Message: array_merge(): Argument #3 must be of type array, null given
File: /home/lxxx/web/xxxx/public_html/SSPanel-Uim/src/Controllers/SubController.php
Line: 345

race

#0 /home/xxxx/web/xxxx/public_html/SSPanel-Uim/src/Controllers/SubController.php(345): array_merge()
#1 /home/xxxx/web/xxxx/public_html/SSPanel-Uim/src/Controllers/LinkController.php(65): App\Controllers\SubController::getClash()
#2 /home/xxxx/web/xxxx/public_html/SSPanel-Uim/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(38): App\Controllers\LinkController::getContent()
#3 /home/xxxx/web/xxxx/public_html/SSPanel-Uim/vendor/slim/slim/Slim/Routing/Route.php(358): Slim\Handlers\Strategies\RequestResponse->__invoke()
#4 /home/xxxx/web/xxxx/public_html/SSPanel-Uim/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\Routing\Route->handle()
#5 /home/xxxx/web/xxxx/public_html/SSPanel-Uim/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Slim\MiddlewareDispatcher->handle()
#6 /home/xxxx/web/xxxx/public_html/SSPanel-Uim/vendor/slim/slim/Slim/Routing/Route.php(315): Slim\MiddlewareDispatcher->handle()
#7 /home/xxxx/web/xxxx/public_html/SSPanel-Uim/vendor/slim/slim/Slim/Routing/RouteRunner.php(68): Slim\Routing\Route->run()
#8 /home/xxxx/web/xxxx/public_html/SSPanel-Uim/src/Middleware/ErrorHandler.php(28): Slim\Routing\RouteRunner->handle()
#9 /home/xxxx/web/xxxx/public_html/SSPanel-Uim/vendor/slim/slim/Slim/MiddlewareDispatcher.php(121): App\Middleware\ErrorHandler->process()
#10 /home/xxxx/web/xxxx/public_html/SSPanel-Uim/vendor/slim/slim/Slim/MiddlewareDispatcher.php(65): Psr\Http\Server\RequestHandlerInterface@anonymous->handle()
#11 /home/xxxx/web/xxxx/public_html/SSPanel-Uim/vendor/slim/slim/Slim/App.php(199): Slim\MiddlewareDispatcher->handle()
#12 /home/xxxx/web/xxxx/public_html/SSPanel-Uim/vendor/slim/slim/Slim/App.php(183): Slim\App->handle()
#13 /home/xxxx/web/xxxx/public_html/SSPanel-Uim/public/index.php(40): Slim\App->run()

请问这是什么情况？

**Comment by lowprofileusername** [comment]
还有升级的时候报错
Current database version 20230201.

Found migration version 2023031701.
Found migration version 2023021600.
Found migration version 2023030500.
Found migration version 2023020100.
Found migration version 20000101000000.
PHP Fatal error:  Uncaught Error: Class "Phinx\Migration\AbstractMigration" not found in /home/xxxx/web/xxxx/public_html/SSPanel-Uim/db/migrations/20000101000000_init_database.php:8
Stack trace:
#0 /home/xxxx/web/xxxx/public_html/SSPanel-Uim/src/Command/Migration.php(85): require_once()
#1 /home/xxxx/web/xxxx/public_html/SSPanel-Uim/xcat(51): App\Command\Migration->boot()
#2 {main}
  thrown in /home/xxxx/web/xxxx/public_html/SSPanel-Uim/db/migrations/20000101000000_init_database.php on line 8

这个是为什么呀
