### ISSUE TITLE
[BUG] ClientDownload 下载失败

### ISSUE THREAD

**Issue by Simonaorg** [Anankke/SSPanel-Uim#1948]
**Environment 环境**
ubuntu 22.04
OS:    2023.2
PHP version:    8.1
DB version:    10.6
Commit:    

**Bug Info**
2023.2 版本中 运行命令 php xcat ClientDownload，显示结果如下：

本地软体版本库 LocalClientVersion.json 不存在，创建文件中...
====== Clash for Windows 开始 ======
- 本地不存在 Clash for Windows，检测到当前最新版本为 0.20.22
目标文件夹 /data/wwwroot/domain.com/app/../public/clients/ 不存在，创建中...
PHP Fatal error:  Uncaught Error: Call to undefined function App\Command\system() in /data/wwwroot/domain.com/src/Command/ClientDownload.php:57
Stack trace:
#0 /data/wwwroot/domain.comp/src/Command/ClientDownload.php(224): App\Command\ClientDownload->getSourceFile()
#1 /data/wwwroot/domain.com/src/Command/ClientDownload.php(45): App\Command\ClientDownload->getSoft()
#2 /data/wwwroot/domain.com/xcat(50): App\Command\ClientDownload->boot()
#3 {main}
  thrown in /data/wwwroot/domain.com/src/Command/ClientDownload.php on line 57

**Comment by Simonaorg** [comment]
> PHP禁用函数，删除 "system" ，重启PHP

  感谢
