### ISSUE TITLE
[BUG]  执行php xcat Migration new出错

### ISSUE THREAD

**Issue by dbGGBoy** [Anankke/SSPanel-Uim#2087]
Forward to 2023020100
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'bigint(20) unsigned NOT NULL DEFAULT 0 COMMENT 'Telegram ID',
               ...' at line 42 in /data/wwwroot/cs/db/migrations/2023020100-init.php:11
Stack trace:
#0 /data/wwwroot/cs/db/migrations/2023020100-init.php(11): PDO->exec()
#1 /data/wwwroot/cs/src/Command/Migration.php(103): App\Interfaces\MigrationInterface@anonymous->up()
#2 /data/wwwroot/cs/xcat(50): App\Command\Migration->boot()
#3 {main}
  thrown in /data/wwwroot/cs/db/migrations/2023020100-init.php on line 11
sql出错求助

**Comment by dbGGBoy** [comment]
服务器类型： MariaDB
服务器版本： 10.11.4-MariaDB-log - MariaDB Server
协议版本： 10
