### ISSUE TITLE
[BUG] 执行初始化设置时出现错误

### ISSUE THREAD

**Issue by ligongfu** [Anankke/SSPanel-Uim#2376]
**Environment 环境**

OS:   Ubuntu 22.04/x86_64
HTTPS enabled:   enabled
PHP version:    8.3
DB version:  MariaDB 11.2
Redis version:    7.2.4
Commit:    commit 613628909365768f467b6a3100d3025dd1ac8ee3 (HEAD, tag: 2023.7)

**Bug Info**

```
# php xcat Migration new
Current database version 0

Found migration version 2023020100
Found migration version 2023060300
Found migration version 2024012300
Found migration version 2023021600
Found migration version 2023081800
Found migration version 2023080900
Found migration version 2023032600
Found migration version 2023071600
Found migration version 2023111801
Found migration version 2024012700
Found migration version 2023071700
Found migration version 2023072000
Found migration version 2023063000
Found migration version 2023031701
Found migration version 2023031700
Found migration version 2023053000
Found migration version 2023061800
Found migration version 2023082000
Found migration version 2023050800
Found migration version 2023111800
Found migration version 2023102200
Found migration version 2023120700
Found migration version 2023111700
Found migration version 2023030500
Found migration version 2024012000
Found migration version 2023071000

Forward to 2023020100
Forward to 2023021600
Forward to 2023030500
Forward to 2023031700
Forward to 2023031701
Forward to 2023032600
Forward to 2023050800
Forward to 2023053000
Forward to 2023060300
Forward to 2023061800
PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'sspanel.user_hourly_usage' doesn't exist in /www/SSPanel-Uim/db/migrations/2023061800-update_new_shop_data_type.php:11
Stack trace:
#0 /www/SSPanel-Uim/db/migrations/2023061800-update_new_shop_data_type.php(11): PDO->exec()
#1 /www/SSPanel-Uim/src/Command/Migration.php(110): App\Interfaces\MigrationInterface@anonymous->up()
#2 /www/SSPanel-Uim/xcat(50): App\Command\Migration->boot()
#3 {main}
  thrown in /www/SSPanel-Uim/db/migrations/2023061800-update_new_shop_data_type.php on line 11
```

**Comment by ligongfu** [comment]
通过更新到dev解决
