### ISSUE TITLE
现在支持后端API 对接吗？

### ISSUE THREAD

**Issue by qiuzi** [Anankke/SSPanel-UIM#2452]

**Comment by Anankke** [comment]
一直都是 WebAPI 对接呀，db 早就废弃了

**Comment by qiuzi** [comment]
使用 V24.5.0就对接不上

**Comment by Anankke** [comment]
我的没问题哦

**Comment by qiuzi** [comment]
> 我的没问题哦
> 
v24.5.1 后端xrayr 0.8.8
前端提示 `/mod_mu/nodes/103/info?key=xxxxxx&muKey=xxxxxxx HTTP/1.1" 500 5305 "-" "go-resty/2.7.0 (https://github.com/go-resty/resty)"`

**Comment by Anankke** [comment]
> > 我的没问题哦
> 
> v24.5.1 后端xrayr 0.8.8 前端提示 `/mod_mu/nodes/103/info?key=xxxxxx&muKey=xxxxxxx HTTP/1.1" 500 5305 "-" "go-resty/2.7.0 (https://github.com/go-resty/resty)"`

500 不给看错误信息怎么帮你呢 👶

**Comment by qiuzi** [comment]
> > > 我的没问题哦
> > 
> > v24.5.1 后端xrayr 0.8.8 前端提示 `/mod_mu/nodes/103/info?key=xxxxxx&muKey=xxxxxxx HTTP/1.1" 500 5305 "-" "go-resty/2.7.0 (https://github.com/go-resty/resty)"`
> 
> 500 不给看错误信息怎么帮你呢 👶 
debug 开启还是xrayr信息？
`Slim 应用程序错误

由于以下错误，应用程序无法运行：

详

类型：ArgumentCountError

法典：0

消息：Redis：：__construct（） 期望正好 0 个参数，给定 1 个

文件：/var/www/html/src/Services/Cache.php

线：13

跟踪

#0 /var/www/html/src/Services/Cache.php(13): Redis->__construct() #1 /var/www/html/src/Services/RateLimit.php(19): App\Services\Cache->initRedis() #2 /var/www/html/src/Middleware/NodeToken.php(36): App\Services\RateLimit->__construct() #3 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(129): App\Middleware\NodeToken->process() #4 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): Psr\Http\Server\RequestHandlerInterface@anonymous->handle() #5 /var/www/html/vendor/slim/slim/Slim/Routing/Route.php(321): Slim\MiddlewareDispatcher->handle() #6 /var/www/html/vendor/slim/slim/Slim/Routing/RouteRunner.php(74): Slim\Routing\Route->run() #7 /var/www/html/src/Middleware/ErrorHandler.php(44): Slim\Routing\RouteRunner->handle() #8 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(129): App\Middleware\ErrorHandler->process() #9 /var/www/html/vendor/slim/slim/Slim/MiddlewareDispatcher.php(73): Psr\Http\Server\RequestHandlerInterface@anonymous->handle() #10 /var/www/html/vendor/slim/slim/Slim/App.php(209): Slim\MiddlewareDispatcher->handle() #11 /var/www/html/vendor/slim/slim/Slim/App.php(193): Slim\App->handle() #12 /var/www/html/public/index.php(40): Slim\App->run() #13 {main}

回去`

**Comment by qiuzi** [comment]
> 也许，可以修改 config/.config.php 文件，暂不使用这个功能
> `
> $_ENV['enable_rate_limit'] = false;     // 是否开启请求限制
> `

改了也无效

**Comment by Anankke** [comment]
你的 php-redis 版本号可能不对，你的 redis 可能也没配好

**Comment by qiuzi** [comment]
> 你的 php-redis 版本号可能不对，你的 redis 可能也没配好

ubuntu 24默认php8.3安装 redis配置也是默认

https://github.com/qiuzi/sspanel/raw/ubuntu-php/Dockerfile
启动脚本
https://github.com/qiuzi/sspanel/raw/ubuntu-php/conf/supervisord.conf
