### ISSUE TITLE
[BUG]最新版DEV，手动设定 每月重置流量失效

### ISSUE THREAD

**Issue by tanyui** [Anankke/SSPanel-Uim#745]
**我确认我已经阅读了** (使用 "x" 选择)

- [x ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ x] 反馈一个 bug
- [x] 申请添加新的特性或功能或者好的想法

![Snipaste_2019-08-03_17-55-29](https://user-images.githubusercontent.com/39109396/62410477-a7ab4300-b618-11e9-89ff-e63e35a2f11f.png)

**您好，更新DEV最新版之后，手动设定 每月某天 重置流量失效。**
演示站无法进行复现

**Comment by Anankke** [comment]
？？？？
需要更多报告

**Comment by tanyui** [comment]
> ???? 
> 需要更多报告

您好，


```
PHP Fatal error:  Uncaught PDOException: SQLSTATE[HY000]: General error: 1267 Illegal mix of collations (latin1_swedish_ci,IMPLICIT) and (utf8_general_ci,COERCIBLE) for operation '=' in /www/wwwroot/***.***/vendor/illuminate/database/Connection.php:480
Stack trace:
#0 /www/wwwroot/***.***/vendor/illuminate/database/Connection.php(480): PDOStatement-&gt;execute(Array)
#1 /www/wwwroot/***.***/vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection-&gt;Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'delete from `ss...', Array)
#2 /www/wwwroot/***.***/vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection-&gt;runQueryCallback('delete from `ss...', Array, Object(Closure))
#3 /www/wwwroot/***.***/vendor/illuminate/database/Connection.php(483): Illuminate\Database\Connection-&gt;run('delete from `ss...', Array, Object(Closure))
#4 /www/wwwroot/***.***/vendor/illuminate/database/Connection.php(438): Illuminate\Database\Connection-&gt;affectingStatement in /www/wwwroot/***.***/vendor/illuminate/database/Connection.php on line 729
----------------------------------------------------------------------------
```
★  xcat checkjob  报错






```
Warning: file_get_contents(http://update.cz88.net/ip/copywrite.rar): failed to open stream: Connection timed out in /www/wwwroot/***.***/app/Command/Job.php on line 232

Warning: file_get_contents(/www/wwwroot/***.***/storage/qqwry.md5): failed to open stream: No such file or directory in /www/wwwroot/***.***/app/Command/Job.php on line 237

Warning: file_get_contents(http://update.cz88.net/ip/qqwry.rar): failed to open stream: Connection timed out in /www/wwwroot/***.***/app/Command/Job.php on line 241
From https://github.com/xcxnig/ssr-download
 * branch            HEAD       -&gt; FETCH_HEAD
Already up-to-date.
----------------------------------------------------------------------------
```
★  xcat dailyjob 报错

**Comment by TBQin** [comment]
你解决了？我现在好像也发现这个问题了
