### ISSUE TITLE
解封封ip超过规定设备数引起的后端问题

### ISSUE THREAD

**Issue by SoulCodes** [Anankke/SSPanel-Uim#766]
**我确认我已经阅读了** (使用 "x" 选择)

- [ ] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [x ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [x ] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

前端启用这段代码
        foreach ($users as $user) {
            $alive_ips = (isset($alive_ipset[$user->id])?$alive_ipset[$user->id]:new \ArrayObject());
            $ips = array();

            $disconnected_ips = explode(",", $user->disconnect_ip);

            foreach ($alive_ips as $alive_ip) {
                if (!isset($ips[$alive_ip->ip]) && !in_array($alive_ip->ip, $disconnected_ips)) {
                    $ips[$alive_ip->ip]=1;
                    if ($user->node_connector < count($ips)) {
                        //暂时封禁
                        $isDisconnect = Disconnect::where('id', '=', $alive_ip->ip)->where('userid', '=', $user->id)->first();

                        if ($isDisconnect == null) {
                            $disconnect = new Disconnect();
                            $disconnect->userid = $user->id;
                            $disconnect->ip = $alive_ip->ip;
                            $disconnect->datetime = time();
                            $disconnect->save();

                            if ($user->disconnect_ip == null||$user->disconnect_ip == "") {
                                $user->disconnect_ip = $alive_ip->ip;
                            } else {
                                $user->disconnect_ip .= ",".$alive_ip->ip;
                            }
                            $user->save();
                        }
                    }
                }
            }
        }

前端启用上面解封ip代码后，后端用的Nimaqu版本，就会导致所有用户端口都暂停，错误日志如下
2019-08-20 15:42:59 ERROR    server_pool.py:99 18133
Traceback (most recent call last):
  File "/soft/shadowsocks/server_pool.py", line 92, in _loop
    loop.run()
  File "/soft/shadowsocks/shadowsocks/eventloop.py", line 228, in run
    callback()
  File "/soft/shadowsocks/shadowsocks/tcprelay.py", line 2049, in handle_periodic
    self._eventloop.removefd(self._server_socket_fd)
  File "/soft/shadowsocks/shadowsocks/eventloop.py", line 181, in removefd
    del self._fdmap[fd]
KeyError: 18133
2019-08-20 15:42:59 INFO     db_transfer.py:822 db start server at port [10003] pass [111111] protocol [origin] method [aes-256-cfb] obfs [http_simple_compatible]
2019-08-20 15:43:03 WARNING  common.py:334 You did't specify CIDR routing prefix size for 124.127.202.190, implicit treated as 124.127.202.190/32
2019-08-20 15:43:03 WARNING  common.py:334 You did't specify CIDR routing prefix size for 219.142.30.210, implicit treated as 219.142.30.210/32
2019-08-20 15:43:03 WARNING  common.py:334 You did't specify CIDR routing prefix size for 219.142.30.230, implicit treated as 219.142.30.230/32
2019-08-20 15:43:03 WARNING  common.py:334 You did't specify CIDR routing prefix size for 

以上错误日志结束后，紧接着，所有端口都会被暂停，屏蔽解封ip代码，清空disconnect_ip信息就稳定工作，但是无法解封ip了。
大佬明示。

**Comment by Anankke** [comment]
没有明白

**Comment by SoulCodes** [comment]
可以问一下里面日志显示的Keyerror怎么打印更详细信息吗？
