### ISSUE TITLE
Slim Application Error

### ISSUE THREAD

**Issue by mashirozx** [Anankke/SSPanel-Uim#844]
**我确认我已经阅读了** (使用 "x" 选择)

- [ x] [项目 Wiki ](https://github.com/Anankke/SSPanel-Uim/wiki)
- [ ] [项目其他 issue](https://github.com/Anankke/SSPanel-Uim/issues?utf8=%E2%9C%93&q=is%3Aissue)

**我确认我做到了** (使用 "x" 选择)

- [ x] [将项目升级到当前分支最新版本](https://github.com/Anankke/SSPanel-Uim/wiki/%E5%8D%87%E7%B4%9A%E7%89%88%E6%9C%AC)
- [ ] 在[项目演示站](https://demo.nimaqu.com)成功复现问题

**我正在申请**  (使用 "x" 选择)

- [ x] 反馈一个 bug
- [ ] 申请添加新的特性或功能或者好的想法

```
Slim Application Error
The application could not run because of the following error:

Details
Type: Error
Message: Class 'Illuminate\Pagination\LengthAwarePaginator' not found
File: /var/www/SSPanel-Uim/vendor/illuminate/database/Eloquent/Builder.php
Line: 495
Trace
#0 /var/www/SSPanel-Uim/app/Controllers/UserController.php(731): Illuminate\Database\Eloquent\Builder->paginate(15, Array, 'page', 1)
#1 [internal function]: App\Controllers\UserController->profile(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#2 /var/www/SSPanel-Uim/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#3 /var/www/SSPanel-Uim/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#4 /var/www/SSPanel-Uim/app/Middleware/Auth.php(23): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#5 [internal function]: App\Middleware\Auth->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#6 /var/www/SSPanel-Uim/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(App\Middleware\Auth), Array)
#7 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#8 /var/www/SSPanel-Uim/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\Route))
#9 /var/www/SSPanel-Uim/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#10 /var/www/SSPanel-Uim/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#11 /var/www/SSPanel-Uim/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#12 /var/www/SSPanel-Uim/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php(70): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#13 [internal function]: Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#14 /var/www/SSPanel-Uim/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware), Array)
#15 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#16 /var/www/SSPanel-Uim/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#17 /var/www/SSPanel-Uim/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#18 /var/www/SSPanel-Uim/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#19 /var/www/SSPanel-Uim/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#20 /var/www/SSPanel-Uim/config/routes.php(390): Slim\App->run()
#21 /var/www/SSPanel-Uim/public/index.php(11): require('/var/www/SSPane...')
#22 {main}
```

**Comment by 573462273** [comment]
自从@TheCGDF修复签到后流量显示异常之后就存在这个错误！

**Comment by mashirozx** [comment]
问题出在 example.com/user/profile 页面，其他页面暂未发现异常

**Comment by TheCGDF** [comment]
@mashirozx 是否方便退回到我commit之前一个版本查看是否有异常？

**Comment by TheCGDF** [comment]
@SakuraSa233 在？出来挨打

https://github.com/Anankke/SSPanel-Uim/commit/093dbc3d4839a797db35e0fa88f7c8a9a56b3e12

为什么把 "illuminate/pagination"删了？

**Comment by TheCGDF** [comment]
> 自从@TheCGDF修复签到后流量显示异常之后就存在这个错误！

CNM

**Comment by regendsoh** [comment]
@TheCGDF xswl

**Comment by mashirozx** [comment]
@TheCGDF 应该不是你的原因，我在大概一周前就已经有这个问题了

**Comment by Anankke** [comment]
@SakuraSa233
