### ISSUE TITLE
[!!!Attention!!!]Breaking changes in recent file database clean

### ISSUE THREAD

**Issue by Incisakura** [Anankke/SSPanel-Uim#918]
In commit b948525, we cleaned the "file database" in `checkJob` to store this data to the database.
There may be some issues remained, please do not apply to production directly.
Please help us to fix potential issues.
To update:
1. Switch to commit after c770185 (some issues fixed)
2. Stop checkJob in cron(comment it).
3. Import sql/job_clean.sql to the database.
4. Backup storage folder.
5. Run `utils/clean_job.php` and check the output(`utils/processed.json`, `utils/raw.json`, `utils/notified.json`)

在 commit b948525，我们清理了checkJob中的“文件数据库”并将其数据储存于数据库中。
这可能留下了些许bug，请不要直接应用于生产环境。
请帮助我们修正可能潜在的 bug。
升级方法：
1. 切换到 c770185 后的 commit (这里修正了一些错误)
2. 停止cron 中的 checkJob (将其注释掉)
3. 将 sql/job_clean.sql 导入至数据库
4. 备份 storage 文件夹
5. 运行 `utils/clean_job.php` 并确认其输出 (`utils/processed.json`, `utils/raw.json`, `utils/notified.json`)

**Comment by Incisakura** [comment]
`utils/processed.json`: Data that processed
`utils/raw.json`: Raw data(not including `traffic_notified`)
`utils/notified.json`: Raw `traffic_notified` data

Also, you need to check the output in the console.

**Comment by Incisakura** [comment]
After commit 864d90d, please import sql/job_clean.sql again.

**Comment by thaizxj** [comment]
Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'offline' in 'field list' in /www/wwwroot//vendor/illuminate/database/Connection.php:478
Stack trace:
#0 /www/wwwroot//vendor/illuminate/database/Connection.php(478): PDO->prepare('update `ss_node...')
#1 /www/wwwroot//vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'update `ss_node...', Array)
#2 /www/wwwroot//vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('update `ss_node...', Array, Object(Closure))
#3 /www/wwwroot//vendor/illuminate/database/Connection.php(483): Illuminate\Database\Connection->run('update `ss_node...', Array, Object(Closure))
#4 /www/wwwroot//vendor/illuminate/database/Connection.php(426): Illuminate\Database\Connection->affectingStatement('update `ss_node...', Array)
#5 /www in /www/wwwroot//vendor/illuminate/database/Connection.php on line 729

执行utils/clean_job.php报错

**Comment by Incisakura** [comment]
@thaizxj 

> 3. Import sql/job_clean.sql to the database.

**Comment by thaizxj** [comment]
已经导入最新的job_clean.sql了

**Comment by xcxnig** [comment]
@thaizxj 为啥offline 不是online吗

**Comment by thaizxj** [comment]
> @thaizxj 为啥offline 不是online吗

不知道呀。。。执行了就是offline

**Comment by Incisakura** [comment]
Please delete all existed columns and import sql again.
`online` name issue may be fixed in a512fd7.

**Comment by thaizxj** [comment]
> Please delete all existed columns and import sql again.
> `online` name issue may be fixed in [a512fd7](https://github.com/Anankke/SSPanel-Uim/commit/a512fd763f2f3ad841dc5f859b46358a33c3bed3).

Renew Process START.Renew Process END.

Offline Process START.PHP Warning:  unlink(/www/wwwroot//utils/../storage/1offline): No such file or directory in /www/wwwroot//utils/clean_job.php on line 50

Warning: unlink(/www/wwwroot//utils/../storage/1offline): No such file or directory in /www/wwwroot//utils/clean_job.php on line 50
Offline Process successed for node1
PHP Warning:  unlink(/www/wwwroot//utils/../storage/2offline): No such file or directory in /www/wwwroot//utils/clean_job.php on line 50

Warning: unlink(/www/wwwroot//utils/../storage/2offline): No such file or directory in /www/wwwroot//utils/clean_job.php on line 50
Offline Process successed for node2
Offline Process END.

Expire Process START.PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'online' in 'field list' in /www/wwwroot//vendor/illuminate/database/Connection.php:478
Stack trace:
#0 /www/wwwroot//vendor/illuminate/database/Connection.php(478): PDO->prepare('update `user` s...')
#1 /www/wwwroot//vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'update `user` s...', Array)
#2 /www/wwwroot//vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('update `user` s...', Array, Object(Closure))
#3 /www/wwwroot//vendor/illuminate/database/Connection.php(483): Illuminate\Database\Connection->run('update `user` s...', Array, Object(Closure))
#4 /www/wwwroot//vendor/illuminate/database/Connection.php(426): Illuminate\Database\Connection->affectingStatement('update `user` s...', Array)
#5 /www/ in /www/wwwroot//vendor/illuminate/database/Connection.php on line 729

Fatal error: Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'online' in 'field list' in /www/wwwroot//vendor/illuminate/database/Connection.php:478
Stack trace:
#0 /www/wwwroot//vendor/illuminate/database/Connection.php(478): PDO->prepare('update `user` s...')
#1 /www/wwwroot//vendor/illuminate/database/Connection.php(722): Illuminate\Database\Connection->Illuminate\Database\{closure}(Object(Illuminate\Database\MySqlConnection), 'update `user` s...', Array)
#2 /www/wwwroot//vendor/illuminate/database/Connection.php(685): Illuminate\Database\Connection->runQueryCallback('update `user` s...', Array, Object(Closure))
#3 /www/wwwroot//vendor/illuminate/database/Connection.php(483): Illuminate\Database\Connection->run('update `user` s...', Array, Object(Closure))
#4 /www/wwwroot//vendor/illuminate/database/Connection.php(426): Illuminate\Database\Connection->affectingStatement('update `user` s...', Array)
#5 /www/ in /www/wwwroot//vendor/illuminate/database/Connection.php on line 729

**Comment by thaizxj** [comment]
这个目录下storage/1offline的文件名错了 正确的是1.offline

**Comment by thaizxj** [comment]
@Incisakura  
Column not found: 1054 Unknown column 'online' in 'field list' in /www/wwwroot//vendor/illuminate/database/Connection.php:478
这个还是未解决  #918

**Comment by Incisakura** [comment]
> Please delete all existed columns and import sql again.

**Comment by thaizxj** [comment]
@Incisakura 
这里应该是$user->expired = false;吧
$user->online = false;应该是错误的。user表里没有online列

**Comment by Anankke** [comment]
@Incisakura is this working?

**Comment by Incisakura** [comment]
Everything should be working after 8ebc9eb.

**Comment by laurieryayoi** [comment]
Expire Process START.PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'expired' in 'field list' in /data/wwwroot/xxxxxx/vendor/illuminate/database/Connection.php:478

**Comment by laurieryayoi** [comment]
expire_notified 不是 expired_notified

**Comment by hsly109** [comment]
Notified Process Nothing to do.
