### ISSUE TITLE
[BUG]用户中心 Clash for Windows 配置文件下载链接报错

### ISSUE THREAD

**Issue by ding0828** [Anankke/SSPanel-Uim#962]
**将 [ ] 替换为 [x] 。Please relpace [ ] with [x] .**

[ x] 我已知晓并同意，如果我不遵循以下格式提交 issue，或者我使用的并非最新版本的 SSPanel UIM，或者我没有提供足够的信息，或者我没有选中这些框，则我的 issue 将会被无条件关闭和锁定。 I acknowledge if I don't follow the format below, or I'm on an old commit, or I fail to provide sufficient information, or I don't check these box, my issue could be closed without any notice.
[ x] 我已确认我已经阅读过使用文档、Wiki，并在 issue 列表中查找相似的问题。I certify that I have read project Wiki and other issue may related to this one.
[ x] 我已知晓并同意，如果我不同意上述条件却仍然提交 issue，或即使同意上述条件但在提交 issue 时不按照条件执行，我的 issue 可被 SSPanel UIM 维护团队视为 spam、并在必要时会被举报到 GitHub。 I acknowledge if I disagree with the conditions above but still submit a issue, or if I agree conditions above but do not follow them when submitting a issue, my issue could be considered as spam by the SSPanel UIM maintenance team, and might be reported to GitHub if necessary.
**Environment 环境
Your OS info, PHP/MySQL version and so on... 你的操作系统信息、PHP/MySQL 版本、以及其它所有可能相关的信息。**

OS: Centos 7.5
MySQL: 5.5.62
PHP: 7.3

**Commit**
The commit you on. 你当前的 SSPanel UIM 位于哪条 commit。

dev commit 54024ba

**Bug
The bug information. 请描述你遇到的 Bug。**

用户中心 Clash for Windows 配置文件下载链接报错
Bug模式信息
```
Slim Application Error
The application could not run because of the following error:

Details
Type: Error
Message: Class 'Symfony\Component\Yaml\Yaml' not found
File: /www/wwwroot/xxxxxxx.com/src/Controllers/ConfController.php
Line: 346
Trace
#0 /www/wwwroot/xxxxxxx.com/src/Controllers/LinkController.php(818): App\Controllers\ConfController::getClashConfs(Object(App\Models\User), Array, Array)
#1 /www/wwwroot/xxxxxxx.com/src/Controllers/LinkController.php(169): App\Controllers\LinkController::getClash(Object(App\Models\User), '1', Array, Array)
#2 [internal function]: App\Controllers\LinkController::GetContent(Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#3 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/Handlers/Strategies/RequestResponse.php(40): call_user_func(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#4 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/Route.php(281): Slim\Handlers\Strategies\RequestResponse->__invoke(Array, Object(Slim\Http\Request), Object(Slim\Http\Response), Array)
#5 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\Route->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#6 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/Route.php(268): Slim\Route->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#7 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/App.php(503): Slim\Route->run(Object(Slim\Http\Request), Object(Slim\Http\Response))
#8 /www/wwwroot/xxxxxxx.com/vendor/zeuxisoo/slim-whoops/src/Zeuxisoo/Whoops/Provider/Slim/WhoopsMiddleware.php(70): Slim\App->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response))
#9 [internal function]: Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#10 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/DeferredCallable.php(57): call_user_func_array(Object(Zeuxisoo\Whoops\Provider\Slim\WhoopsMiddleware), Array)
#11 [internal function]: Slim\DeferredCallable->__invoke(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#12 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(70): call_user_func(Object(Slim\DeferredCallable), Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Slim\App))
#13 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/MiddlewareAwareTrait.php(117): Slim\App->Slim\{closure}(Object(Slim\Http\Request), Object(Slim\Http\Response))
#14 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/App.php(392): Slim\App->callMiddlewareStack(Object(Slim\Http\Request), Object(Slim\Http\Response))
#15 /www/wwwroot/xxxxxxx.com/vendor/slim/slim/Slim/App.php(297): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response))
#16 /www/wwwroot/xxxxxxx.com/public/index.php(34): Slim\App->run()
#17 {main}
```

Reproduce
Steps to reproduce the bug. 请逐步描述如何复现 Bug。

Expected behavior
What you expected to happen. 请描述你预期的行为。

Logs
If applicable, add your PHP logs here. 如果需要，请在这里粘贴 PHP Log。

Addition
Additional context here. 如有可能，请提供更多相关资料。

**Comment by ding0828** [comment]
已解决

**Comment by ding0828** [comment]
已解决

**Comment by Topcckin** [comment]
> 已解决

请问一下怎么解决的啊？我最近也出现这个问题了，不知道哪里出问题了，大佬能说一下怎么解决吗，谢谢。
